# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from builtins import dict
from typing import Any, Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired

SessionId: TypeAlias = str


EventId: TypeAlias = str


JobId: TypeAlias = str


Locale: TypeAlias = str


Region: TypeAlias = str


SemVer: TypeAlias = str


Channel: TypeAlias = Literal["web", "android", "ios"]


Band: TypeAlias = Literal["A", "B", "C"]


SessionStatus: TypeAlias = Literal[
    "created",
    "connected",
    "in_progress",
    "verifying",
    "passed",
    "failed",
    "inconclusive",
    "expired",
    "aborted",
]


Decision: TypeAlias = Literal["pass", "fail", "inconclusive"]


ChallengeKind: TypeAlias = Literal[
    "head_turn",
    "distance",
    "fingers",
    "digits",
    "blink",
    "expression",
    "hand_over_face",
    "look_profile",
]


ReasonCode: TypeAlias = str


ErrorCode: TypeAlias = Literal[
    "unauthorized",
    "forbidden_scope",
    "ip_not_allowed",
    "rate_limited",
    "validation_error",
    "idempotency_conflict",
    "tenant_suspended",
    "policy_version_unknown",
    "session_not_found",
    "webhook_not_found",
    "job_not_found",
    "session_not_cancellable",
    "result_pending",
    "evidence_expired",
    "webhook_limit",
    "internal_error",
]


class Problem(TypedDict):
    type: str
    title: str
    status: int
    detail: str
    code: ErrorCode
    request_id: str


class Overrides(TypedDict):
    min_actions: NotRequired[int]
    languages: NotRequired[list[Locale]]


class SessionPolicy(TypedDict):
    version: NotRequired[int]
    overrides: NotRequired[Overrides]


class IngestHint(TypedDict):
    country: NotRequired[str]


class Callback(TypedDict):
    url: str
    secret_ref: NotRequired[str]


class EvidenceRequest(TypedDict):
    audit_frames: NotRequired[bool]
    clip: NotRequired[bool]
    retention_days: NotRequired[int]


class IngestCandidate(TypedDict):
    region: Region
    url: str


class PackRef(TypedDict):
    lang: Locale
    version: str
    url: str


class ConsentCopy(TypedDict):
    title: str
    body: str
    recording_notice: str


class Brand(TypedDict):
    primary: str
    logo_url: str | None


class Session(TypedDict):
    session_id: SessionId
    status: SessionStatus
    created_at: str
    connected_at: str | None
    ended_at: str | None
    verdict_at: str | None
    policy_version: int
    channel: Channel
    ingest_region: str | None
    band: Literal["A", "B", "C"] | None
    metadata: dict


class SessionPage(TypedDict):
    data: list[Session]
    next_cursor: str | None


class ReasonDetail(TypedDict):
    code: ReasonCode
    severity: str
    text: str


class ChallengeResult(TypedDict):
    id: str
    kind: ChallengeKind
    result: str
    attempts: int
    latency_ms: int


class Quality(TypedDict):
    lighting: Literal["low", "ok", "bright"]
    face_size: str
    network_rung_median: int
    received_fps_median: float


class Device(TypedDict):
    platform: Channel
    attested: bool
    attestation_verdict: str | None


Models: TypeAlias = dict[str, str]


class ResultEvidence(TypedDict):
    audit_frames: int
    clip: bool
    expires_at: str | None


class EvidenceChallenge(TypedDict):
    idx: int
    id: str
    kind: ChallengeKind
    params: dict[str, Any]
    result: str
    attempts: int
    latency_ms: int
    scores: dict[str, float]


class SignedUrl(TypedDict):
    url: str
    expires_at: str


class SubjectPurge(TypedDict):
    user_ref: str


class Job(TypedDict):
    job_id: JobId
    kind: Literal["subject_purge"]
    status: Literal["pending", "running", "succeeded", "failed"]
    created_at: str
    completed_at: str | None


WebhookEventType: TypeAlias = Literal[
    "zakadi.session.completed", "zakadi.session.aborted", "zakadi.session.expired"
]


class WebhookCreate(TypedDict):
    url: str
    events: list[WebhookEventType]
    secret: str
    active: NotRequired[bool]


class WebhookUpdate(TypedDict):
    url: str
    events: list[WebhookEventType]
    active: bool
    secret: NotRequired[str]


class Webhook(TypedDict):
    webhook_id: str
    url: str
    events: list[WebhookEventType]
    secret_ref: str
    active: bool
    created_at: str


class WebhookList(TypedDict):
    data: list[Webhook]


class WebhookDelivery(TypedDict):
    webhook_id: str
    event_id: EventId
    attempt: int
    status: int | None
    error: str | None
    at: str


class WebhookDeliveryPage(TypedDict):
    data: list[WebhookDelivery]
    next_cursor: str | None


class PolicyActions(TypedDict):
    min: int
    max: int
    pool: list[ChallengeKind]
    step_up_pool: list[ChallengeKind]
    require_geometry: bool
    require_high_entropy: bool


class PolicyAssurance(TypedDict):
    accept_bands: list[Band]
    web_allowed: bool
    attestation_required: bool


class PolicyThresholds(TypedDict):
    profile: Literal["balanced", "strict", "lenient"]


class PolicyAttempts(TypedDict):
    per_action: int
    restarts: int
    sessions_per_user_ref_per_day: int
    sessions_per_face_per_day: int


class PolicyStepUp(TypedDict):
    enabled: bool
    human_handoff: bool
    handoff_url: str | None


class PolicyRetention(TypedDict):
    results_days: int
    evidence_days_default: int
    evidence_days_max: int
    evidence_clip_allowed: bool
    embeddings_days: int


class PolicyDedupe(TypedDict):
    enabled: bool
    cross_session_face_match: bool


class PlayIntegrity(TypedDict):
    cloud_project_number: str
    verify: Literal["google_api", "local"]
    credentials_ref: str


class AppAttest(TypedDict):
    team_id: str
    bundle_id: str


class PolicyAttestation(TypedDict):
    play_integrity: NotRequired[PlayIntegrity]
    app_attest: NotRequired[AppAttest]


class PolicyResidency(TypedDict):
    ingest_regions: list[Region]
    gpu_regions: list[Region]
    in_country_only: bool


class PolicyUi(TypedDict):
    character: Literal["default", "none"]
    brand: Brand
    badge_text: str | None


class UsageRow(TypedDict):
    day: str
    channel: Channel
    band: Literal["A", "B", "C"] | None
    status: SessionStatus
    count: int


ProtocolItem: TypeAlias = str


class Probe(TypedDict):
    count: int
    bytes: int


class QuirkMatch(TypedDict):
    platform: NotRequired[Channel]
    model_prefix: NotRequired[str]
    browser: NotRequired[str]
    browser_major_min: NotRequired[int]
    browser_major_max: NotRequired[int]
    os_major_min: NotRequired[int]
    os_major_max: NotRequired[int]


class QuirkCaps(TypedDict):
    max_fps: NotRequired[int]
    max_rung: NotRequired[int]
    profile: NotRequired[Literal["mediarecorder"]]
    prefer_software_encoder: NotRequired[bool]


class Wrapper(TypedDict):
    name: str
    version: str


class SdkIdentity(TypedDict):
    platform: Channel
    name: str
    version: str
    os: NotRequired[str]
    device: NotRequired[str]
    browser: NotRequired[str]
    wrapper: NotRequired[Wrapper]


class TelemetryEvent(TypedDict):
    name: str
    t_ms: int
    fields: NotRequired[dict[str, Any]]


class Health(TypedDict):
    status: Literal["ok"]


class RegionHealth(TypedDict):
    region: Region
    healthy: bool
    headroom: float


class Jwk(TypedDict):
    kty: Literal["EC"]
    crv: Literal["P-256"]
    kid: str
    use: Literal["sig"]
    alg: Literal["ES256"]
    x: str
    y: str


class SessionCreate(TypedDict):
    user_ref: str
    locale: Locale
    channel: Channel
    device_correlation_id: NotRequired[str]
    policy: NotRequired[SessionPolicy]
    ingest_hint: NotRequired[IngestHint]
    callback: NotRequired[Callback]
    metadata: NotRequired[dict]
    evidence: NotRequired[EvidenceRequest]


class SessionUi(TypedDict):
    consent_copy: dict[str, ConsentCopy]
    brand: Brand
    badge_text: str | None
    packs: list[PackRef]


class ResultData(TypedDict):
    session_id: SessionId
    decision: Decision
    band: Literal["A", "B", "C"] | None
    confidence: float | None
    reason_codes: list[ReasonCode]
    reasons_detail: list[ReasonDetail]
    challenges: list[ChallengeResult]
    quality: Quality | None
    device: Device | None
    models: Models
    policy_version: int
    verdict_at: str
    evidence: ResultEvidence
    metadata: dict
    superseded: NotRequired[bool]


class Result(ResultData):
    result_token: str


class SessionEvidence(TypedDict):
    session_id: SessionId
    scores: dict[str, float]
    forensics: dict[str, float]
    timing: dict[str, Any]
    challenges: list[EvidenceChallenge]
    audit_frames: list[SignedUrl]
    clip: SignedUrl | None
    expires_at: str


class WebhookEvent(TypedDict):
    id: EventId
    type: WebhookEventType
    created_at: str
    data: ResultData
    result_token: str


class PolicySettings(TypedDict):
    actions: PolicyActions
    assurance: PolicyAssurance
    thresholds: PolicyThresholds
    attempts: PolicyAttempts
    step_up: PolicyStepUp
    languages: list[Locale]
    retention: PolicyRetention
    dedupe: PolicyDedupe
    attestation: NotRequired[PolicyAttestation]
    residency: PolicyResidency
    ui: PolicyUi


class Policy(PolicySettings):
    version: int


Usage = TypedDict(
    "Usage",
    {
        "from": str,
        "to": str,
        "data": list[UsageRow],
    },
)


class DeviceQuirk(TypedDict):
    match: QuirkMatch
    caps: QuirkCaps


class TelemetryBatch(TypedDict):
    session_id: SessionId
    sdk: SdkIdentity
    events: list[TelemetryEvent]


class IngestHealth(TypedDict):
    regions: list[RegionHealth]


class Jwks(TypedDict):
    keys: list[Jwk]


class SessionCreated(TypedDict):
    session_id: SessionId
    client_token: str
    expires_at: str
    ingest: list[IngestCandidate]
    prompt_pack: PackRef
    ui: SessionUi
    policy_version: int
    status: SessionStatus


class SdkConfig(TypedDict):
    min_version: SemVer
    latest_version: SemVer
    kill_switch: bool
    wrapper_min_version: dict[str, SemVer]
    message: str | None
    protocol: list[ProtocolItem]
    prompt_pack_cdn: str
    probe: Probe
    ladder_version: int
    device_quirks: list[DeviceQuirk]
